apiVersion: apps/v1
kind: Deployment
metadata:
  name: ems
  labels:
    app: ems-tomcat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ems-tomcat
  template:
    metadata:
      labels:
        app: ems-tomcat
    spec:
      containers:
      - name: ems-app
        image: varakumar/ems:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: svc1
  labels:
      app: ems-tomcat
spec:
  selector:
    app: ems-tomcat
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer
